import { Product, Shipment } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-1',
    name: 'เซ็ตเบเกอรี่และของหวานจิ๋ว Miniature Bakery Set',
    description: 'อุปกรณ์ขนมปัง เค้ก ถาดอบ และเครื่องครัวของจิ๋วสเกล 1:12 ดีเทลสวยประณีต สำหรับแต่งบ้านตุ๊กตา Sylvanian ให้ดูอบอุ่นน่ารัก',
    price: 490,
    image_url: 'https://images.unsplash.com/photo-1581557991964-125469da3b8a?q=80&w=1000&auto=format&fit=crop',
    category: 'ของจิ๋ว',
    condition: 'มือ 1',
    size_category: null,
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
  },
  {
    id: 'mock-2',
    name: 'Sylvanian Families - Chocolate Rabbit Family',
    description: 'ครอบครัวกระต่ายช็อกโกแลตตัวยอดนิยม ของแท้ 100% มือหนึ่งในกล่องซีล ประกอบด้วยคุณพ่อ คุณแม่ พี่สาว และเบบี้ ชุดเสื้อผ้าน่ารักตัดเย็บประณีต ขนนุ่มสภาพสมบูรณ์',
    price: 1290,
    image_url: 'https://images.unsplash.com/photo-1558877385-81a1c7e67d72?q=80&w=1000&auto=format&fit=crop',
    category: 'ชุดเซ็ต',
    condition: 'มือ 1',
    size_category: 'Adults',
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
  },
  {
    id: 'mock-3',
    name: 'ตุ๊กตาเบบี้ช็อกโกแลตแรบบิท ตัวเปล่า',
    description: 'น้องเบบี้กระต่ายช็อกโกแลตตัวเปล่า ขนฟูนุ่ม ไม่มีรอยเปื้อน สภาพสะสม 98% ตัวจริงน่ารักมาก เหมาะสำหรับนำไปแต่งตัวคัสตอมหรือสะสม',
    price: 290,
    image_url: 'https://images.unsplash.com/photo-1560859251-d563a49c5e4a?q=80&w=1000&auto=format&fit=crop',
    category: 'ตัวเปล่า',
    condition: 'มือ 2',
    size_category: 'Baby',
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'mock-4',
    name: 'บ้านหลังใหญ่ Red Roof Country Home',
    description: 'บ้านหลังคาสีแดงเปิดไฟได้ สภาพสวยมาก 95%+ อุปกรณ์ครบ ไม่มีตำหนิหักพัง พับเปิด-ปิดปรับโครงสร้างห้องได้หลายแบบ พร้อมกล่องเดิม',
    price: 2450,
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1000&auto=format&fit=crop',
    category: 'บ้าน',
    condition: 'มือ 2',
    size_category: null,
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
  },
  {
    id: 'mock-5',
    name: 'ชุดเดรสเจ้าหญิงคัสตอมพร้อมที่คาดผมดอกไม้',
    description: 'ชุดเสื้อผ้าสั่งตัดพิเศษสำหรับฟิกเกอร์ไซส์พี่สาว Sylvanian งานแฮนด์เมดตัดเย็บละเอียด ลายลูกไม้สีชมพูหวานละมุน สวมใส่ง่าย',
    price: 350,
    image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000&auto=format&fit=crop',
    category: 'เสื้อผ้า',
    condition: 'มือ 1',
    size_category: 'Children',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    name: 'ซองสุ่มเบบี้คอลเลกชัน Baby Blind Bag Series',
    description: 'ซองสุ่มตุ๊กตาเบบี้ Sylvanian Families ลุ้นตัวละครลับและไอเทมสุดน่ารัก ของแท้ 100% ซองซีลยังไม่แกะ สนุกกับการลุ้นสะสม',
    price: 220,
    image_url: 'https://images.unsplash.com/photo-1558877385-81a1c7e67d72?q=80&w=1000&auto=format&fit=crop',
    category: 'ซองสุ่ม',
    condition: 'มือ 1',
    size_category: 'Baby',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-7',
    name: 'ยกบ็อกซ์เบบี้คอสตูม Baby Costume Series (ครบเซ็ต 8 ซอง)',
    description: 'ยกกล่องซีลใหม่ 100% บรรจุ 8 ซอง ลุ้นครบทุกคาแรคเตอร์พร้อมตัว Secret ตัวแท้จาก Shop พร้อมกล่อง Display สวยงาม',
    price: 1690,
    image_url: 'https://images.unsplash.com/photo-1560859251-d563a49c5e4a?q=80&w=1000&auto=format&fit=crop',
    category: 'ยกบ็อกซ์',
    condition: 'มือ 1',
    size_category: 'Baby',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: 'ship-1',
    customer_name: 'ชลธิชา มั่นคง',
    shipping_date: new Date().toISOString().split('T')[0],
    carrier: 'Flash Express',
    tracking_number: 'TH01495829482A',
    note: 'ชุดเซ็ตซิลวาเนียน 2 รายการ',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ship-2',
    customer_name: 'กนกวรรณ แสนสุข',
    shipping_date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    carrier: 'Kerry Express (KEX)',
    tracking_number: 'KEX503928194',
    note: 'บ้านตุ๊กตา Red Roof',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'ship-3',
    customer_name: 'ธนภัทร วงศ์สวรรค์',
    shipping_date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    carrier: 'ไปรษณีย์ไทย (EMS/ลงทะเบียน)',
    tracking_number: 'ED839201948TH',
    note: 'ตุ๊กตาเบบี้ช็อกโกแลตแรบบิท',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'ship-4',
    customer_name: 'สุพรรณี เจริญพร',
    shipping_date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    carrier: 'Flash Express',
    tracking_number: 'TH01928471928B',
    note: 'ของจิ๋วเบเกอรี่',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];
