import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-1',
    name: 'เซ็ตเบเกอรี่และของหวานจิ๋ว Miniature Bakery Set (มือ 1)',
    description: 'อุปกรณ์ขนมปัง เค้ก ถาดอบ และเครื่องครัวของจิ๋วสเกล 1:12 ดีเทลสวยประณีต สำหรับแต่งบ้านตุ๊กตา Sylvanian ให้ดูอบอุ่นน่ารัก',
    price: 490,
    image_url: 'https://images.unsplash.com/photo-1581557991964-125469da3b8a?q=80&w=1000&auto=format&fit=crop',
    category: 'ของจิ๋ว',
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
  },
  {
    id: 'mock-2',
    name: 'Sylvanian Families - Chocolate Rabbit Family (มือ 1 กล่องสวย)',
    description: 'ครอบครัวกระต่ายช็อกโกแลตตัวยอดนิยม ของแท้ 100% มือหนึ่งในกล่องซีล ประกอบด้วยคุณพ่อ คุณแม่ พี่สาว และเบบี้ ชุดเสื้อผ้าน่ารักตัดเย็บประณีต ขนนุ่มสภาพสมบูรณ์',
    price: 1290,
    image_url: 'https://images.unsplash.com/photo-1558877385-81a1c7e67d72?q=80&w=1000&auto=format&fit=crop',
    category: 'ชุดเซ็ต',
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
  },
  {
    id: 'mock-3',
    name: 'ตุ๊กตาเบบี้ช็อกโกแลตแรบบิท ตัวเปล่า (มือ 2 สภาพนางฟ้า)',
    description: 'น้องเบบี้กระต่ายช็อกโกแลตตัวเปล่า ขนฟูนุ่ม ไม่มีรอยเปื้อน สภาพสะสม 98% ตัวจริงน่ารักมาก เหมาะสำหรับนำไปแต่งตัวคัสตอมหรือสะสม',
    price: 290,
    image_url: 'https://images.unsplash.com/photo-1560859251-d563a49c5e4a?q=80&w=1000&auto=format&fit=crop',
    category: 'ตัวเปล่า',
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'mock-4',
    name: 'บ้านหลังใหญ่ Red Roof Country Home (มือ 2 สภาพนางฟ้า)',
    description: 'บ้านหลังคาสีแดงเปิดไฟได้ สภาพสวยมาก 95%+ อุปกรณ์ครบ ไม่มีตำหนิหักพัง พับเปิด-ปิดปรับโครงสร้างห้องได้หลายแบบ พร้อมกล่องเดิม',
    price: 2450,
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1000&auto=format&fit=crop',
    category: 'บ้าน',
    is_active: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
  },
  {
    id: 'mock-5',
    name: 'ชุดเดรสเจ้าหญิงคัสตอมพร้อมที่คาดผมดอกไม้ (มือ 1)',
    description: 'ชุดเสื้อผ้าสั่งตัดพิเศษสำหรับฟิกเกอร์ไซส์พี่สาว Sylvanian งานแฮนด์เมดตัดเย็บละเอียด ลายลูกไม้สีชมพูหวานละมุน สวมใส่ง่าย',
    price: 350,
    image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000&auto=format&fit=crop',
    category: 'เสื้อผ้า',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
